### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by onlyshow** [openzipkin/docker-zipkin#183] opened 2018-07-13 08:00 UTC
![5ad0e9e4-6f80-4a4c-a02b-a4cf0561f753](https://user-images.githubusercontent.com/12505832/42679877-f2373a7a-86b5-11e8-9792-285719985918.png)

`    image: "openzipkin/zipkin"`

**Comment by adriancole** [comment] 2018-07-13 11:02
This is a duplicate of https://github.com/openzipkin/zipkin/issues/1911
except for the type error which isn't reported anywhere yet as far as I
know.

If you can try to help remove the type error (perhaps by upgrade) go for
it! If not, you can raise an issue on https://github.com/openzipkin/zipkin
for it?

**Closed by adriancole** 2018-07-13 11:02 UTC
